FROM balenalib/raspberrypi3-python:3-build

RUN install_packages \
        unzip

WORKDIR /usr/src/app
RUN git clone https://github.com/CodeLinkIO/bsec_bme680_linux.git
WORKDIR /usr/src/app/bsec_bme680_linux
RUN chmod +x make.sh
RUN ./make.sh

RUN pip install smbus w1thermsensor enviroplus RPi.GPIO

WORKDIR /usr/src/app
COPY ./scripts ./scripts
COPY ./entry.sh /usr/src/app/
RUN chmod +x /usr/src/app/entry.sh

CMD ["./entry.sh"]
